### PR TITLE
Add support for Ubuntu 22.04

### PR DESCRIPTION
**Pull request by grant-veepshosting**
#### Pull Request (PR) description
Add support for Ubuntu 22.04, compatible with 22.04 template.

#### This Pull Request (PR) fixes the following issues
Ubuntu LTS compatibility.

### CODE REVIEW

**Comment by smortex** [comment]
This module does weird things like shipping a different config for each OS / version of an OS so this is likely to fail:
https://github.com/voxpupuli/puppet-fail2ban/tree/master/templates/Ubuntu

I suggest:
1. wait for the 22.04 version to become available;
2. adjust [voxpupuli/puppet_metadata](https://github.com/voxpupuli/puppet_metadata) and release a new version that is aware of this new release;
3. have CI working for this work and fix it.

**Comment by tarjei** [comment]
@smortex is the thing this is waiting for Puppet to have builds for 22.04?

**Comment by smortex** [comment]
@tarjei thanks for the heads up… Looks like I messed with my tabs when reviewing a bunch of PR including this one (was probably linking this to another PR that just updated metadata.json to add Ubuntu 22.04 support).

**Review by smortex — APPROVED** [review]
That's probably fine and can supposedly be merged as is.  The next Puppet release should have [Ubuntu 22.04 support](https://tickets.puppetlabs.com/browse/PA-4233), so maybe we can also wait for that release and add it to `metadata.json` so that the test suite run against it?

**Comment by brunoleon** [comment]
Can you merge this now the 22.04 support is there ?

**Comment by smortex** [comment]
Thanks for the heads up @brunoleon!

I added a commit so that Support for this version of Ubuntu is visible and to allow the test suite to test against this version.  Unfortunately, some work is needed to fix CI (because the branch is old, it is merged with the current master before the test suite start).

@grant-veepshosting Can you please rebase your branch on top of the main one?

From your branch in your fork:

```
git pull               # Get the commit I added on top of your fork
git remote add vox https://github.com/voxpupuli/puppet-fail2ban.git # Add a "vox" remote for this repo
git fetch vox          # Download the latest code we have here
git rebase vox/master  # Move your commits on top of the main branch
git push -f            # Send the changes (-f is required because we re-wrote history)
```

Then the line number is the CI report will make sense and fixing the issue will be possible.

Thanks!

**Comment by grant-veepshosting** [comment]
Done now, thanks for providing the steps and your patience - busy start to the week.

**Comment by smortex** [comment]
Nice, thanks!  The remaining CI failure should be easy to fix :wink:, do you mind give it a try?

```

Failures:

  1) fail2ban on ubuntu-22.04-x86_64 is expected to contain Class[fail2ban] with config_file_template => "a new os.name or os.release.major needs a new case"
     Failure/Error: it { is_expected.to contain_class('fail2ban').with_config_file_template('a new os.name or os.release.major needs a new case') }
       expected that the catalogue would contain Class[fail2ban] with config_file_template set to "a new os.name or os.release.major needs a new case" but it is set to "fail2ban/Ubuntu/22.04/etc/fail2ban/jail.conf.epp"
     # ./spec/classes/init_spec.rb:43:in `block (4 levels) in <top (required)>'

Finished in 18.17 seconds (files took 11.33 seconds to load)
525 examples, 1 failure
```

https://github.com/voxpupuli/puppet-fail2ban/blob/9cd8afc00b404c5a36a0d962723cd61613d4211b/spec/classes/init_spec.rb#L37-L44

**Review by smortex — APPROVED** [review]
LGTM

**Pull request merged**
