### PR TITLE
Don't use the template source file name in the templates

### LINKED ISSUE #29: Template header causes service restart
The template headers contain the file path:

```
#
# THIS FILE IS MANAGED BY PUPPET
# <%= file %>
#
```

This path is interpreted as the server side file path:
```
/etc/puppetlabs/code/environments/*********/fail2ban/templates/xenial/etc/fail2ban/jail.conf
```
and is placed on a client-side file

this causes one of two issues:

1. Bleeds puppetmaster internal file structure over to the agents unnecessarily
2. Whenever you change the node's environment (eg for debugging purposes) if you use directory environments, this causes the file path to change from
```
/etc/puppetlabs/code/environments/env1/modules/fail2ban/templates/xenial/etc/fail2ban/jail.conf
```
to
```
/etc/puppetlabs/code/environments/env2/modules/fail2ban/templates/xenial/etc/fail2ban/jail.conf
```
and this causes a subsequent (unnecessary) service restart:

```
Info: Computing checksum on file /etc/fail2ban/jail.conf
Info: /Stage[main]/Fail2ban::Config/File[fail2ban.conf]: Filebucketed /etc/fail2ban/jail.conf to puppet with sum 49cf86b38fbf358131a35d93da5cb9bb
Notice: /Stage[main]/Fail2ban::Config/File[fail2ban.conf]/content: content changed '{md5}49cf86b38fbf358131a35d93da5cb9bb' to '{md5}48402a8a8491bcb926c3be3667a0d7bc'
Info: /Stage[main]/Fail2ban::Config/File[fail2ban.conf]: Scheduling refresh of Service[fail2ban]
Info: Class[Fail2ban::Config]: Scheduling refresh of Class[Fail2ban::Service]
Info: Class[Fail2ban::Service]: Scheduling refresh of Service[fail2ban]
```

I'm more than happy to fork the repo and submit a PR fixing this, however I'd like to know what you think is the best solution. I would just remove the file path comment entirely.

### PR DESCRIPTION
**Pull request by arjenz**
Using the full path to the template in the files changes the file
every time puppet runs against a different environment, remove
<%= file %> everywhere

Fixes #29

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @arjenz,thanks for the PR. Can you please rebase?

**Comment by arjenz** [comment]
@bastelfreak Done

**Comment by arjenz** [comment]
Rebased current master again, anything else I can do? :)

**Comment by arjenz** [comment]
The new `.epp` templates don't have the file reference anymore it appears.

**Pull request closed without merging**
