### PR TITLE
Account for RedHat variants

### LINKED ISSUE #23: Support for OracleLinux
Being a rebuild of RH it's a simple matter of patching config.pp.

```diff
--- config.pp.bak	2017-01-17 13:15:40.681058922 -0500
+++ config.pp	2017-01-17 13:16:06.890730918 -0500
@@ -38,7 +38,7 @@
 
   # Operating system specific configuration
   case $::operatingsystem {
-    /^(RedHat|CentOS|Scientific)$/: {
+    /^(RedHat|CentOS|Scientific|OracleLinux)$/: {
       # Not using firewalld by now
       file { '00-firewalld.conf':
         ensure  => 'absent',

```

### PR DESCRIPTION
**Pull request by decibelhertz**
#### Pull Request (PR) description
#23 breaks my unit testing for my company's *profile* class since this module fails when testing defaults against Redhta variants other than CentOS.

I suggest a simple override of OEL/Rocky/Alma/etc to use CentOS templates to reduce repeat template maintenance.  Reworked hiera.yaml and `data` to use modern PDK standard file, and created overrides there.  Explicit testing in rspec needed similar logic

#### This Pull Request (PR) fixes the following issues
Fixes #23

### CODE REVIEW

**Comment by decibelhertz** [comment]
I see that #176 addresses the multiple jail.conf issue too.  I could simplify this PR if that PR goes through.

**Comment by traylenator** [comment]
@decibelhertz so there's nothing left here ?

**Comment by decibelhertz** [comment]
I think #177 resolves this better.  If you accept that PR, close this out; no need for this one.

**Comment by traylenator** [comment]
Obsoleted by #177

**Pull request closed without merging**
