### PR TITLE
Install redhat-lsb-core to provide additional facts

### LINKED ISSUE #88: Could not find template 'fail2ban/stretch/etc/fail2ban/jail.conf.erb'
Good day

It looks like templates are renamed to epp, but then you get 

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Could not find template 'fail2ban/stretch/etc/fail2ban/jail.conf.erb' (file: /etc/puppetlabs/code/modules/fail2ban/manifests/init.pp, line: 44, column: 26) on node REMOVED

### LINKED ISSUE #102: Could not find template 'fail2ban//etc/fail2ban/jail.conf.erb' - CentOS Linux release 7.6.1810 (Core)
**CentOS Linux release 7.6.1810 (Core)**

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Could not find template 'fail2ban//etc/fail2ban/jail.conf.erb'

### PR DESCRIPTION
**Pull request by dhoppe**
Fixes #88 
Fixes #102

### CODE REVIEW

**Comment by traylenator** [comment]
Have you considered just using the standard $facts['os'] ?

**Comment by dhoppe** [comment]
@traylenator I did but they do not contain the codename of a release, which is used to point to the correct ```.epp``` template. 

* https://github.com/camptocamp/facterdb/blob/master/facts/3.11/centos-7-x86_64.facts#L442-L460

We could use a different directory structure like ```templates/$facts['os']['name']/$facts['os']['release']['major']/etc/fail2ban/jail.conf.epp``` but this would be a backwards incompatible change.

**Comment by traylenator** [comment]
Why backwards incompatible?

Is it not just an internal rearrangement of file locations of the templates

I'll have a better look at the module before I comment any more.

**Comment by dhoppe** [comment]
@traylenator Yes, but it affects the use because he has to change his configuration. Otherwise the templates will not be found.

**Comment by bastelfreak** [comment]
I'm not a big fan of the lsb facts. I think proper version numbers are a better approach, because those are always available and don't need additional packages. Note: The next release will already be a major one because it includes backwards-incompatible changes. But also we should not do too many of them if we can avoid it.

**Comment by gcoxmoz** [comment]
Forcing RedHat servers to install lsb-core is just the wrong direction.

- Facter gives us facts about the OS, there's no reason we need an extra package installed.
- The answers that lsb-core gives are incomplete: CentOS is `$facts['os']['family'] == 'RedHat'` but lsb always calls it 'Core', so we can't distinguish between CentOS7 and CentOS8 by just the lsb name.

So, this PR adds an extra package to preserve a status quo that needs to go away.

**Comment by neomilium** [comment]
Please note that official puppet documentation mention that:

```
Linux: use the lsb_release utility and parse the contents of release files in /etc to retrieve the OS information.
```
https://puppet.com/docs/puppet/latest/core_facts.html#os

So, should we really skip the need of `lsb_release`?

IMHO, it should not be a requirement of this module but its requirement of Puppet/Facter…

**Pull request closed without merging**
