### PR TITLE
Changed tag in ignoreip to printing

### PR DESCRIPTION
**Pull request by sternj**
#### Pull Request (PR) description
Fixes a minor issue which made it so that, when ignoreip was specified as a parameter in a YAML file containing custom jails, it was still not written to the yaml file

#### This Pull Request (PR) fixes the following issues
n/a

### CODE REVIEW

**Comment by bastelfreak** [comment]
HI @sternj, thanks for the PR! Could you add a little unit test to verify that the template now works as expected?

**Comment by sternj** [comment]
@bastelfreak It doesn't look like there are any unit tests whatsoever for this functionality, nor any way to check stuff pulled in from Hiera files. The closest thing I can find is starting on line 25 of `/spec/defines/fail2ban_jail_spec.rb`, which states
```ruby
it do
        is_expected.to contain_file('custom_jail_spec_test_jail').with(
          'ensure'  => 'file',
          'notify'  => 'Service[fail2ban]',
          'content' => %r{\[spec_test_jail\]}
        )
      end
```

I can't tell what file this is checking. I can't find any other references to custom jails in the test suite. Is there something I'm missing here?

**Comment by bastelfreak** [comment]
You can create a new context block and provide the parameter, afterwards you can check if a certain line is present in the file resource:

https://github.com/voxpupuli/puppet-fail2ban/blob/c9be79e6e3a3abc5813cba48cc6038e9b22df655/spec/defines/define_spec.rb#L30-L40

**Comment by sternj** [comment]
resolved in 0ebaa61538f

**Pull request closed without merging**
