### PR TITLE
Consolidate classes - atomic

### PR DESCRIPTION
**Pull request by Phil-Friderici**
This patch consolidates the all classes into the main class as mentioned in issue #17.
Each commit did pass all spec tests.

It also adds missing resources to the tests to reach full resource coverage.

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
closing this in favour of https://github.com/dhoppe/puppet-fail2ban/pull/21

**Comment by Phil-Friderici** [comment]
@dhoppe will rework the spec tests to better reflect the consolidated classes once you have agreed to it.

**Comment by dhoppe** [comment]
@Phil-Friderici I know that this module need to be refactored and that the best practices change over time, but could you explain to me why you made these changes? I really do not like to put all the code into one file. 

If I take a look at the PuppetConf talks the params.pp might be obsolete, but install/config/service is still valid and the differences between operating systems might be put into single files which are included if necessary.

**Comment by Phil-Friderici** [comment]
@dhoppe Thanks for reviewing my PR :)

The reason for the consolidation is explained in https://github.com/dhoppe/puppet-fail2ban/issues/17. 
For easier tracking, I recommend to continue the discussions inside the issue.

**Comment by bastelfreak** [comment]
Hi @Phil-Friderici. This module got recently migrated to Vox Pupuli. Years passed by and style guide recommendations changed. Our latest style guide is at https://voxpupuli.org/docs/#reviewing-a-module-pr. We don't want to use validate_* functions anymore and use datatypes nowdays.

Are you stil interested in this PR? If so, could you please rebase and switch to datatypes instead of validate_* calls?

**Comment by Phil-Friderici** [comment]
Forwarind the question to @ghoneycutt still interested in this PR ?

**Comment by Phil-Friderici** [comment]
Sorry guys, I will not continue to work on this PR any time soon. Closing it too keep the house clean ;)

**Pull request closed without merging**
